### ISSUE TITLE
Mapping terminology

### ISSUE THREAD

**Issue by iglazer** [cronical/idpro-bok-tech-arch#1]
While I love the terminology section, some terms feel proprietary and do not map to products or services in the market nor do the map to commonly used terms. For example, Relying Service is not a commonly used term nor its abbreviation RSVC; terms of are at Relying Party or Service Provider.

My suggestion is to map niche terms to more common ones or adopt the comment ones. Terms I would focus on:
* Relying Service - use RP/SP
* Access governance is more commonly referred to Identity Governance and Administration - IGA... never seen AGOV before

Additionally the abbreviation are introduced in this doc but never used. I would recommend removing

**Comment by cronical** [comment]
Those are exactly the comments I was looking for.  I think I made up a few of those so I would have been surprised if they had any currency :)

**Comment by cronical** [comment]
changed as suggested, but kept all abbreviations as they will be used by use-cases.
