### ISSUE TITLE
Provisioning

### ISSUE THREAD

**Issue by iglazer** [cronical/idpro-bok-tech-arch#2]
The description of provisioning feels academic and hard to process.

The first sentence, "Provisioning describes how the data gets into the identity repository and how it flows further on to support authorization decisions." 

Consider the following definition from Gartner: https://www.gartner.com/en/information-technology/glossary/user-provisioning 

Provisioning is the process by which an IMS (actually an IGA or user provisioning service) manages a user account and associate attributes (including those used for authorization) in a managed/target system, potentially based on data from "upstream" authoritative source. It is an admin-time and not a run-time affair.

One way that this section could be made to be easier to parse is to label steps in the diagram tied to different paragraphs in the section. 

Lastly I would strong recommend clearly separating run-time admin-time processes.

**Comment by cronical** [comment]
I think we should debate the run-time/admin time a little.  The whole just-in-time scenario in my view is a form of provisioning but it happens at run-time. 

I'll take a look at the Gartner bit and make some adjustments.

**Comment by cronical** [comment]
Added governance to diagram and text.  distinguished admin-time, run-time.  Improved the definition without restricting it to users as gartner did.
