### ISSUE TITLE
The “scope” of an IMS

### ISSUE THREAD

**Issue by iglazer** [cronical/idpro-bok-tech-arch#3]
I have discovered what may be the one of the roots of my challenge with this article... the document combines all functions of digital identity into a singular thing called an IMS. 

This aggregation is accurate from an academic perspective but does not reflect actual deployment architectures. Run-time and admin-time systems are mostly separated into different sub-systems and components. They are "joined" by an identity repository which may include credentials.

Furthermore combining everything into a singular IMS does not bring to light the separate nature of workforce vs CIAM deployments.

Long way 'round I *think* more language in the beginning of this document to emphasis it is a conceptual architecture would go a long way. Additionally mapping aspects of this architectural model to the model in Part 3 of the Intro to Identity would help as well.

**Comment by cronical** [comment]
Stressing conceptual seems like a good idea - I'll see what I can do.  

Being comprehensive is kinda the point but I see how it could be misconstrued.

**Comment by cronical** [comment]
Various revisions to stress the conceptual nature of the model.   Separated the CSP and Enrolment functions consistent with the Identity Stack from Part 3 (which is still not published and not certain it should be).  

 NIST 800-63A has combined enrolment and CSP.  Not yet resolved. 

Continue to work on matching these concepts and making revisions.

**Comment by cronical** [comment]
CSP definition - according to NIST.  New issue for Identity stack rationalize
