### ISSUE TITLE
Step-up Authentication deserves a sub-section

### ISSUE THREAD

**Issue by iglazer** [cronical/idpro-bok-tech-arch#4]
The paragraph on step-up Auth in the AuthN section is good but definitely could be expanded. Further, it ought to be a sub-section as it is sandwiched in between 2 session paragraphs.

If it gets its own sub-section I would recommend expanding it to discuss the notional concept of strength of authentication and MFA

**Comment by cronical** [comment]
Will review. Seems right.

**Comment by cronical** [comment]
e-ordered and elaborated on step-up
