### ISSUE TITLE
Attribute Provider is undefined

### ISSUE THREAD

**Issue by iglazer** [cronical/idpro-bok-tech-arch#6]
Please add Attribute Provider to the Terminology

One important note is that an attribute provider could be a user provisioning connector or a directory - that's a damn broad range and that range needs to be called out

**Comment by cronical** [comment]
Excellent addition to the model.  Will do.

**Comment by cronical** [comment]
Included in the definition of Identity Information Authority: "Sometimes the authority for attributes is distinguished from the authority for identities.  In this case the term Attribute Provider is sometimes used.  "
