### ISSUE TITLE
Access governance may be too narrowly defined

### ISSUE THREAD

**Issue by iglazer** [cronical/idpro-bok-tech-arch#7]
While the first sentence of the 1st paragraph is spot the second constrains the topic artificially. Access Governance can be defined to unified access certification, role management, and user provisioning. The way I read the 1st paragraph limits it to user provisioning (and maybe access certification.)

**Comment by cronical** [comment]
Will take a look.  Intended to be holistic.  Probably some elaboration and rework needed.

**Comment by cronical** [comment]
Elaborated to ensure more inclusive.  Same with definition.
