### ISSUE TITLE
Metadata and Discovery - too industry specific

### ISSUE THREAD

**Issue by iglazer** [cronical/idpro-bok-tech-arch#9]
This section feels far too heavily influenced by Higher Ed and Government. 

Metadata is defined too narrowly - metadata can be used to establish trust - but it can also be used to describe what Access Governance services an entity provides (e.g. SCIM metadata) or how to configure an OpenID Connect service (e.g. OIDC metadata.) 

Discovery service as described is not a common service within private sector enterprise and isn't standardized per se. I worry this is too specific to a subset of deployments.

**Comment by cronical** [comment]
Yeah, this is good feedback.  I was a little lost on this and you've provided some perspective.  I will make some changes.

**Comment by cronical** [comment]
Worked in examples from OIDC. Other improvements.
